### PR TITLE
add an svg icon for AKS

### PR DESCRIPTION
**Pull request by flynnduism**
Added an icon based off of the latest logo for AKS. As per previous VS Code icons, this is a transparent, greyscale icon with the original purple color removed.

## Icon

Screen Shot 2020-01-31 at 10 58 05 AM

---

## Config

I was going to add this snippet to the package.json, based off of what I have seen you do in other VS Code extensions, but there are enough differences in this extension that I worry I may break something. I'll wait for @itowlson to weigh in.

```
"viewsContainers": {
    "activitybar": [
        {
            "id": "aks-tools",
            "icon": "./resources/aks-tools.svg",
            "title": "AKS Tools"
        }
    ]
}
```
---

Signed-off-by: flynnduism <flynnduism@gmail.com>

### CODE REVIEW

**Comment by flynnduism** [comment]
Closes #3.

**Comment by itowlson** [comment]
@flynnduism Sorry for the confusion.  This extension doesn't need an activity bar icon (i.e. NOT the left hand nav bar).  #3 is for a _marketplace_ icon, i.e. when they search or download.  Colour is fine; I think we've used PNG rather than SVG in the past but I can test with SVG if you want.  (And this would go in the top level `icon` attribute in `package.json`.)

**Comment by flynnduism** [comment]
🤦‍♂ 

Sorry Ivan, silly of me. Here are two options for the marketplace image, either AKS on white or an inverted style that is common for Azure-affiliated extensions. Pick whichever you prefer.

aks-tools-invert
aks-tools-white

**Comment by itowlson** [comment]
I like the inverted (white-on-purple) design, and it would be good to follow other Azure-affiliated extensions.  (And the flat colour background would save us from going round and round on transparency.)  @philliphoff @daniv-msft you folks are closer to the Azure branding than I am - do you have a view on which of the above designs would be a better fit for the AKS VS Code extension?

**Comment by philliphoff** [comment]
My personal preference is for the non-square purple-on-white icon, as that seems to be the bulk of the icons I see for Azure related extensions in the marketplace (with a couple of exceptions).

Screen Shot 2020-02-04 at 2 56 38 PM

**Comment by flynnduism** [comment]
Closing this in favour of #20.

**Comment by flynnduism** [comment]
Thanks @philliphoff, purple-on-white it is then!

**Pull request closed without merging**
