### PR TITLE
Deprecation/Appreciation of Azure SDK packages.

### PR DESCRIPTION
**Pull request by Tatsinnit**
This PR intend to upgrade Azure SDK and get rid of deprecated packages. Hence inturn take care of this https://github.com/Azure/vscode-aks-tools/issues/14

For the future relevance I am adding extra note: the conversion is fairly bumpy transition (this advice did came handy to me when I was doing this work)

Avoid any manual type conversions: this is very important because whole `azure/arm` ecosystem is built differently so in case of any shortcuts, there will be internal un-bubbled errors which user will just go in loop to resolve. 

There are also bunch of undocumented stuff like: For example: `SubscriptionClietnts` which previously part of `azure-arm-resrouces` is now part of `azure/arm-subscription` and instead of this `SubscriptionClient.SubscriptionModels` its just `SubcriptionModels`  

cc: @itowlson :)  

Build looks cleaner: no deprecation warnings:

Screen Shot 2021-03-04 at 5 59 58 PM

I have given some test as well and seems like things are working fine. (here are some screenshots. 

Screen Shot 2021-03-04 at 2 17 36 PM
Screen Shot 2021-03-04 at 2 19 12 PM
Screen Shot 2021-03-04 at 2 18 31 PM

### CODE REVIEW

**Comment by Tatsinnit** [comment]
💡 cc: @bwateratmsft ; for visibility. = )

**Review by bwateratmsft — APPROVED** [review]
Looks good to me!

**Comment by kanika1894** [comment]
It looks good to me. Can you please share the VSIX, I'll cross check the user experience as well.

**Comment by Tatsinnit** [comment]
> It looks good to me. Can you please share the VSIX, I'll cross check the user experience as well.

Thanks for checking and sounds great @kanika1894 , Please check your `msft` email I cannot send the `vsix` on your `github` account for some reason.

**Comment by kanika1894** [comment]
image
None of the kubernetes assets are getting loaded. 🤔

**Comment by Tatsinnit** [comment]
Thanks @kanika1894 It seems you are missing kubernetes extension or your VSIX is not correctly installed in vscode. @kanika1894 thanks, are you sure you have kubernetes extension installed as well? Can you please ping me in teams? Beside GitHub emails I am not sure what’s the best channel to ping you? (Or I hope you unzipped the extension as *.VSIX and then installed it. (Long shot but asking anyways) 

I will get someone at my end to vanilla test this in his/her machine.

**Comment by kanika1894** [comment]
There was some VSCode version related issue which was causing the above problem.
Thanks to @Tatsinnit for helping me find it.
All good now ✌🏼

**Review by kanika1894 — APPROVED** [review]

**Review by itowlson — APPROVED** [review]
Looks good to me!  Thanks!

**Pull request merged**
