### PR TITLE
package.json: Update Inspektor Gadget version to 0.27.0

### PR DESCRIPTION
**Pull request by blanquicet**
Inspektor Gadget version https://github.com/inspektor-gadget/inspektor-gadget/releases/tag/v0.27.0 was released. Let's bring all its new features and optimizations here.

### CODE REVIEW

**Review by Tatsinnit — APPROVED** [review]
Thank you so much @blanquicet for this, looks good.

**Comment by blanquicet** [comment]
> Thank you so much @blanquicet for this, looks good. Possibily need testing, I can try this sometime latter tomorrow.

Maybe it's the time to start thinking on a small set of tests in the CI so that every update is straightforward?

**Comment by Tatsinnit** [comment]
> > Thank you so much @blanquicet for this, looks good. Possibily need testing, I can try this sometime latter tomorrow.
> 
> Maybe it's the time to start thinking on a small set of tests in the CI so that every update is straightforward?

100 % nice idea and Indeed, let me add more as we can treat that as separate handle which we should definitely handle, there are few interesting thing to think and test for CI build for AKS specific Cluster so I would love CI for AKS cluster spin and if we can test that as scenario test at repo level makes nice improvements.

**Comment by Tatsinnit** [comment]
💡 Closing this PR because latest if recently updated under this PR: https://github.com/Azure/vscode-aks-tools/pull/1047 - Thanks heaps.

**Pull request closed without merging**
