### PR TITLE
Changes to publish 1.4.10.

### PR DESCRIPTION
**Pull request by Tatsinnit**
This PR is for the release `1.4.10`, please see the details below.

* Fix for walkthrough and show welcome dependency.
* Fix U/X Bugs.
* Incremental In-Progress KAITO Work.
* Dependabot updates and bumps.

Thanks all.

### CODE REVIEW

**Review by ReinierCC — APPROVED** [review]

**Review by tejhan — APPROVED** [review]

**Comment by Tatsinnit** [comment]
💡 ❤️  VSIX to play around please: [vscode-aks-tools-1.4.10-test.vsix.zip](https://github.com/user-attachments/files/17121544/vscode-aks-tools-1.4.10-test.vsix.zip)

Thanks heaps!

**Review by ReinierCC — APPROVED** [review]
LGTM, tested VSIX

**Review by tejhan — APPROVED** [review]
Tested vsix, looks good 👍

**Review by hsubramanianaks — APPROVED** [review]
Looks good to me, Thanks @Tatsinnit

**Pull request merged**
