### PR TITLE
Kaito - Additional error handling & manual quota checks

### PR DESCRIPTION
**Pull request by tejhan**
- Added new & refactored existing error handling scenarios 
- Implemented manual quota checking for more detailed user feedback
- Refactored helper functions & updated llama2 crd templates
- Minor UX tweaks

</img>

### CODE REVIEW

**Comment by tejhan** [comment]
V6 for testing 👉 -->  [vscode-aks-tools-1.4.10-kaitoerrors.zip](https://github.com/user-attachments/files/17301967/vscode-aks-tools-1.4.10-kaitoerrors.zip)

**Comment by tejhan** [comment]
This PR currently includes commits from [#963]. Please review this PR after [#963] is merged so the relevant changes here can be reviewed individually. 👐

**Review by Tatsinnit — COMMENTED** [review]
💡 Thank you so much for this, leaving this as a note only: I think this PR is heavily dependent off #963  so once that gets in this PR will cut short in size decently. Hence, I've reviewed the #963 for now. ❤️ 🙏

**Comment by tejhan** [comment]
Superceeded by PR #1003.

**Pull request closed without merging**
